//arat

	SHOP_PRICELIST_MAX_NUM = 40,

//ekle

#ifdef __OFFLINE_PRIVATE_SHOP_SYSTEM__
	OFFLINE_SHOP_HOST_ITEM_MAX_NUM	= 80,
	OFFLINE_SHOP_MAX_COUNT			= 100000,
	OFFLINE_SHOP_SAVE_TIME			= 5,
	OFFLINE_SHOP_DEFAULT_TIME		= 86400,
	OFFLINE_SHOP_NEED_LEVEL			= 15,
	OFFLINE_SHOP_NEED_ITEM			= 71049,
#endif